language: python
python:

  - "3.7"      # current default Python on Travis CI
  
services:
  - docker

before_script:
pip install docker compose

# command to install dependencies

script:
  - docker compose run app sh -c "python manage.py test && flake8"

